
OBJS += frontends/ast/ast.o
OBJS += frontends/ast/simplify.o
OBJS += frontends/ast/simplify_eval.o
OBJS += frontends/ast/simplify_inner.o
OBJS += frontends/ast/simplify_mem.o
OBJS += frontends/ast/simplify_package.o
OBJS += frontends/ast/genrtlil.o
OBJS += frontends/ast/genrtlil_process.o
OBJS += frontends/ast/dpicall.o
OBJS += frontends/ast/ast_binding.o

